version: '2'
services:
  apptest-app:
    image: apptest
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://apptest-mysql:3306/apptest?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://apptest-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://apptest-elasticsearch:9200
    ports:
      - 8080:8080
  apptest-mysql:
    extends:
      file: mysql.yml
      service: apptest-mysql
  apptest-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: apptest-elasticsearch
